---
title: "Preparation"

date: "4/2/2022"
output: html_document
---

```{r echo = F}
library(knitr)

opts_chunk$set(
  fig.align = "center",
  fig.retina = 5,
  warning = F,
  message = F,
  cache = T,
  echo = F,
  fig.cap = TRUE
)
```

```{r echo = F}
#=== Packages ===#
library(sf)
library(data.table)
library(dplyr)
library(data.table)
library(modelsummary)
library(patchwork)
library(flextable)
library(officedown)
library(here)
library(officer)
library(latex2exp)
source(here("./Code/functions.R"))
```

```{r load field info, include=FALSE}
field_year_ls <- c("Larson_EB2_2017",
                   "Larson_OC1_2018",
                   "Larson_BF2_2020",
                   "Nelson_Dougshome_2017",
                   "Nelson_Dougshome_2021",
                   "Nelson_Wirth_2020",
                   "Nelson_DJWest_2021",
                   "Rohrscheib_Almy_2018",
                   "Rohrscheib_AlmyMain_2020",
                   "Rohrscheib_Brach_2016",
                   "Sasse_JensenEast_2016",
                   "Sasse_JensenEast_2018",
                   "Sasse_JensenEast_2020",
                   "Sasse_JensenWest_2017",
                   "Sasse_JensenWest_2021",
                   "Gingerich_Malcarne1_2017",
                   "Gingerich_Malcarne1_2019",
                   "Gingerich_Field2_2018",
                   "Wendte_LaueLib80_2017",
                   "Wendte_LaueLib80_2019",
                   "Wendte_LaueLib80_2021",
                   "Wendte_Snider_2018",
                   "Bohnhoff_Adams_2016",
                   "Bohnhoff_Adams_2018",
                   "Bohnhoff_Adams_2020",
                   "Bohnhoff_Schormann_2016",
                   "Bohnhoff_Schormann_2018",
                   "Bohnhoff_Schormann_2020",
                   "Bohnhoff_Tims_2017",
                   "Bohnhoff_Tims_2019",
                   "Hord_F98_2017",
                   "Hord_F98_2019",
                   "Hord_F98_2021",
                   "Hord_F17_2018",
                   "Hord_F17_2020", 
                   "Hord_F104_2021", 
                   "Niese_98xTom_2018",
                   "Overton_Richter77_2017"
)

all_field_data <- data.table()
for (i in 1:length(field_year_ls)) {
  print(i)
  all_field_data <- rbind(all_field_data, data_summary(field_year_ls[i]))
}
all_field_data <- all_field_data%>%
                         mutate(
                         region = case_when(
                         farm == "Bohnhoff" | farm == "Wendte" ~ "Southern_Illinois",
                         farm == "Larson" | farm == "Nelson"   ~ "Northern_Illinois",
                         farm == "Gingerich" | farm == "Overton" | 
                         farm == "Rohrscheib" | farm == "Sasse" ~ "Central_Illinois",
                         farm == "Hord" | farm == "Niese"   ~ "Ohio"
                         ),
                         state = case_when(
                         farm == "Bohnhoff" | farm == "Wendte" |
                         farm == "Larson" | farm == "Nelson" | 
                         farm == "Gingerich" | farm == "Overton" | 
                         farm == "Rohrscheib" | farm == "Sasse" ~ "Illinois",
                         farm == "Hord" | farm == "Niese"   ~ "Ohio"
                         ))

all_field_data <- left_join(all_field_data, mrtn, by = c('region', 'year'))

saveRDS(all_field_data,here("./Data/all_field_data.rds"))
```
